import type { BuildingType, BuildingDef } from '../types';

export const BUILDINGS: Record<BuildingType, BuildingDef> = {
  coalPlant: {
    name: 'Coal Power Plant',
    cost: 450,
    maintenance: 25,
    powerSupply: 120,
    jobs: 30,
    pollution: 30,
    approval: -5,
    allowedTiles: ['plain', 'coal'],
  },
  gasPlant: {
    name: 'Gas Power Plant',
    cost: 600,
    maintenance: 35,
    powerSupply: 90,
    jobs: 20,
    pollution: 14,
    approval: -2,
    allowedTiles: ['plain', 'gas'],
  },
  windFarm: {
    name: 'Wind Farm',
    cost: 500,
    maintenance: 18,
    powerSupply: 45,
    pollution: 0,
    approval: 3,
    allowedTiles: ['plain', 'hills'],
    terrainBonus: {
      hills: 25, // Extends power output on hills
    },
  },
  solarFarm: {
    name: 'Solar Grid',
    cost: 400,
    maintenance: 12,
    powerSupply: 35,
    pollution: 0,
    approval: 2,
    allowedTiles: ['plain', 'farmland'],
  },
  battery: {
    name: 'Battery Storage',
    cost: 700,
    maintenance: 20,
    reliabilityBonus: 12,
    pollution: 0,
    allowedTiles: ['plain', 'coal', 'gas'],
  },
  housing: {
    name: 'Housing District',
    cost: 300,
    maintenance: 10,
    populationCapacity: 500,
    powerDemand: 25,
    approval: 2,
    allowedTiles: ['plain', 'farmland'],
  },
  industry: {
    name: 'Industrial Zone',
    cost: 350,
    maintenance: 15,
    jobs: 120,
    income: 80,
    powerDemand: 55,
    pollution: 18,
    approval: -2,
    allowedTiles: ['plain', 'coal', 'gas'],
  },
  park: {
    name: 'Park & Preserve',
    cost: 250,
    maintenance: 12,
    environment: 15,
    approval: 5,
    allowedTiles: ['forest', 'plain', 'river'],
  },
  hydroDam: {
    name: 'Hydroelectric Dam',
    cost: 800,
    maintenance: 40,
    powerSupply: 150,
    jobs: 15,
    pollution: 0,
    approval: 5,
    environment: 5,
    allowedTiles: ['river'],
  },
  tidalTurbine: {
    name: 'Tidal Turbine',
    cost: 400,
    maintenance: 15,
    powerSupply: 40,
    jobs: 5,
    pollution: 0,
    approval: 2,
    allowedTiles: ['beach'],
  },
  waveConverter: {
    name: 'Wave Converter',
    cost: 350,
    maintenance: 12,
    powerSupply: 30,
    jobs: 5,
    pollution: 0,
    approval: 2,
    allowedTiles: ['beach'],
  },
  marineGeothermal: {
    name: 'Geothermal Well',
    cost: 900,
    maintenance: 50,
    powerSupply: 160,
    jobs: 10,
    pollution: 0,
    approval: 4,
    allowedTiles: ['hills', 'river'],
  },
  boardwalk: {
    name: 'Beach Boardwalk',
    cost: 300,
    maintenance: 15,
    income: 45,
    jobs: 40,
    powerDemand: 15,
    approval: 8,
    allowedTiles: ['beach'],
  },
  stadium: {
    name: 'Grand Stadium',
    cost: 1000,
    maintenance: 60,
    income: 120,
    jobs: 100,
    powerDemand: 60,
    approval: 15,
    allowedTiles: ['plain'],
  },
  speedway: {
    name: 'Solar Speedway',
    cost: 850,
    maintenance: 45,
    income: 100,
    powerSupply: 30,
    powerDemand: 20,
    jobs: 60,
    pollution: 5,
    approval: 10,
    allowedTiles: ['plain', 'hills'],
  },
  wasteEnergy: {
    name: 'Waste-to-Energy',
    cost: 600,
    maintenance: 30,
    powerSupply: 65,
    jobs: 25,
    pollution: 10,
    approval: -1,
    allowedTiles: ['plain', 'coal'],
  },
  biofuelRefinery: {
    name: 'Biofuel Refinery',
    cost: 500,
    maintenance: 20,
    powerSupply: 50,
    jobs: 30,
    pollution: 8,
    approval: 1,
    allowedTiles: ['farmland', 'plain'],
  },
  fusionReactor: {
    name: 'Fusion Reactor',
    cost: 2000,
    maintenance: 120,
    powerSupply: 500,
    jobs: 80,
    pollution: 0,
    approval: 10,
    allowedTiles: ['plain', 'hills'],
  },
  datacenter: {
    name: 'Cloud Datacenter',
    cost: 750,
    maintenance: 40,
    income: 150,
    jobs: 50,
    powerDemand: 120,
    approval: 2,
    allowedTiles: ['plain', 'hills'],
  },
  supercapacitor: {
    name: 'Supercapacitor',
    cost: 500,
    maintenance: 15,
    reliabilityBonus: 20,
    pollution: 0,
    allowedTiles: ['plain', 'coal', 'gas'],
  },
};
